// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"github.com/tommylike/apaxrag/app/application"
	user2 "github.com/tommylike/apaxrag/app/domain/user"
	"github.com/tommylike/apaxrag/app/infrastructure/user"
	"github.com/tommylike/apaxrag/app/interfaces/api/handler"
	"github.com/tommylike/apaxrag/app/interfaces/api/router"
	"github.com/tommylike/apaxrag/injector/api"
)

// Injectors from wire.go:

func BuildApiInjector() (*ApiInjector, func(), error) {
	db, cleanup, err := InitGormDB()
	if err != nil {
		return nil, nil, err
	}
	repository := user.NewRepository(db)
	service := user2.NewService(repository)
	applicationUser := application.NewUser(service)
	handlerUser := handler.NewUser(applicationUser)
	healthCheck := handler.NewHealthCheck()
	routerRouter := router.NewRouter(handlerUser, healthCheck)
	engine := api.InitGinEngine(routerRouter)
	apiInjector := NewApiInjector(engine)
	return apiInjector, func() {
		cleanup()
	}, nil
}
